spring:
  application:
    name: provider
eureka:
  client:
    serviceUrl:
    #注册中心地址
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2